### PR TITLE
RFC: disable IPv6 on bridge links before adding them to bridge

### PR DESCRIPTION
**Pull request by troglobit**
Not sure if this is the correct way to fix this, but something like this I think.  We don't want to have slaac addresses on the bridge ports.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@BarbarossaTM: What do you think?

**Comment by Neustradamus** [comment]
@kaniini: What do you think? @BarbarossaTM has requested you...

**Comment by troglobit** [comment]
Been almost a year, so I take it this is not an addition to the project you want. I made this PR to check if you're interested in outside collaboration, which is obviously not the case. We've also moved on since then, so closing.

**Comment by kaniini** [comment]
I’m sorry, I get tens of thousands of github emails a week.  Pinging me in IRC will get my attention.

Overall, the patch looks fine and we can pull it in.

**Comment by Neustradamus** [comment]
@kaniini: A lot of people remove PRs because no project management by team and a lot of improvements lost to all.

**Pull request closed without merging**
