### PR TITLE
Man pages for B.A.T.M.A.N. adv., bridges, ethtool, VRFs

### PR DESCRIPTION
**Pull request by BarbarossaTM**
Signed-off-by: Maximilian Wilhelm <max@sdn.clinic>

### CODE REVIEW

**Review by blakedot — COMMENTED** [review]
```
# EXAMPLES

A VRF interfaces:
```
to
```
# EXAMPLES

A VRF interface:
```

**Review by blakedot — COMMENTED** [review]
suggest changing `"The following options allow to set up VRFs and configured interfaces to be part of a VRF"`
to `"The following options allow setting up VRFs and adding configured interfaces to VRFs."`

`"Note that in Linux VRFs are represented as network interfaces, too."`
to `"Note that in Linux's interfaces(5) file, VRFs are represented as network devices similarly to interfaces."`

`"# VRF RELATED OPTIONS ..."`
to
`"# VRF-RELATED OPTIONS"`

`"This parameter indicates that the interface where it is specified shall be a VRF."`
to
`"This parameter indicates that the iface stanza where it is specified is a VRF."`

`"*vrf* _vrf interface_ ..."`
to
```
"*vrf* _vrf iface_
The _vrf_ a regular interface should be assigned to. This parameter is specified on interfaces that are to be within the _vrf-table_ created above."
```

**Comment by kaniini** [comment]
> `"Note that in Linux VRFs are represented as network interfaces, too."`
> to `"Note that in Linux's interfaces(5) file, VRFs are represented as network devices similarly to interfaces."`

I would suggest "VRFs are managed as network devices in the interfaces(5) file."

**Review by kaniini — APPROVED** [review]
Needs rebase but this looks fine.

**Pull request merged**
