### PR TITLE
VRRP support v1.0

### PR DESCRIPTION
**Pull request by EasyNetDev**
Hi,

I added first version of VRRP executor for ifupdown-ng.

### CODE REVIEW

**Comment by Neustradamus** [comment]
To follow

**Comment by Neustradamus** [comment]
@BarbarossaTM: What do you think?

**Comment by EasyNetDev** [comment]
Hi all,

This patch is using a user side VRRP naming. I'm testing another version with is using hex CRC32 name generation from physical interface: v${IFACE_CRC32}-${VRRP_ID_HEX}-4 and v${IFACE_CRC32}-${VRRP_ID_HEX}-6 automatization, where HEX_CRC32 is a function similar to this:

crc32_hex() {
        printf "%08x" $(echo $1 | ${_cksum} | cut -f1 -d" ")
}

IFACE_CRC32=$(crc32_hex ${IFACE})
VRRP_ID_HEX=$(printf "%02x" $VRRP_ID)

IFACE_VRRP_4="v${IFACE_CRC32}-${VRRP_ID_HEX}-4"
IFACE_VRRP_6="v${IFACE_CRC32}-${VRRP_ID_HEX}-6"

This approach is also good because the generation of the names for VRRP is the same over reboots. 
The problem is that I have no clue if is portable to different distros, even cksum should be something common on most of OSes.

Any ideas?

**Comment by EasyNetDev** [comment]
Closing this one via the new patch submitted #222

**Pull request closed without merging**
