### PR TITLE
dist/openrc: Improve service script

### PR DESCRIPTION
**Pull request by fluvf**
See commit messages for details.

I don't feel strongly about the last commit, it can freely be left out if it's found to be undesirable

### CODE REVIEW

**Comment by fluvf** [comment]
I've used this on my machine for a few months now, and haven't encountered any problems.

**Comment by Neustradamus** [comment]
Dear @ifupdown-ng, @BarbarossaTM: What do you think?

**Comment by EasyNetDev** [comment]
Hi @kaniini @BarbarossaTM @awilfox: any updates / thoughts about this PR?

**Comment by EasyNetDev** [comment]
There are already 4 months from last comment and NOBODY is answering or looking on these patches from the admins??

**Pull request merged**
